### ISSUE TITLE
HW3000 vs HW2000

### ISSUE THREAD

**Issue by garudaonekh** [flameqi/hw3000#1]
Hi,
Thanks for the only HW3000 code for Arduino on Github.

By the way, does this code also compatible with HW2000?

thanks;

**Comment by flameqi** [comment]
Thanks for your question.I don't have HW2000 module. So I can't do something for HW2000.发自我的荣耀手机-------- 原始邮件 --------发件人： GarudaOne ***@***.***>日期： 2024年2月22日周四 晚上8:17收件人： flameqi/hw3000 ***@***.***>抄送： Subscribed ***@***.***>主    题： [flameqi/hw3000] HW3000 vs HW2000 (Issue #1)
Hi,
Thanks for the only HW3000 code for Arduino on Github.
By the way, does this code also compatible with HW2000?
thanks;

**Comment by garudaonekh** [comment]
thanks for your input.
