### ISSUE TITLE
Is HW3000 compatible with HW2000

### ISSUE THREAD

**Issue by garudaonekh** [flameqi/hw3000#2]
Hi,
I got the HW2000 code from the vendor. It's in STM32 format. I only know Arduino.
Would you take a look if it's compatible with your HW3000 or let me know how to migrate it to Arduino.

[HW2000B_Easy_Demo_v1.1.zip](https://github.com/flameqi/hw3000/files/14496699/HW2000B_Easy_Demo_v1.1.zip)

Thanks

**Comment by flameqi** [comment]
Sorry! I'm so busy for my work. suggest: Read the Datasheet of HW2000B ,and modify demo for arduino

**Comment by garudaonekh** [comment]
Thanks;

**Comment by flameqi** [comment]
Thank you bro! 
I add this mission (compatible with HW2000) to my todo list in  this summer vacation. When finished the mission, I will sent code to you.
从 Windows 版邮件发送

发件人: GarudaOne
发送时间: 2024年3月12日 23:28
收件人: flameqi/hw3000
抄送: flame.qi; Comment
主题: Re: [flameqi/hw3000] Is HW3000 compatible with HW2000 (Issue #2)

Thanks;
